# Setup
title: Help Carroll Gardens Heights
url: patrickgeorge5.github.io

# Custom vars
github:
  repo: https://github.com/patrickgeorge5/carrollgardensbk.com

sass:
  # Where you keep your scss files
  sass_dir: /
  # Where SASS should look for other SCSS
  load_paths:
    - node_modules/
